import turtle
#Screen
a = turtle.Screen()
a.bgcolor('pink')

pen=turtle.Turtle()
#kotak tongkat
pen.down()
pen.fillcolor('Brown')
pen.begin_fill()
pen.forward(10)
pen.left(90)
pen.forward(50)
pen.left(90)
pen.forward(10)
pen.left(90)
pen.forward(50)
pen.end_fill()
pen.up()

#Kotak Kuning
pen.left(180)
pen.forward(50)
pen.down()
pen.fillcolor('Yellow')
pen.begin_fill()
pen.left(90)
pen.forward(80)
pen.right(45)
pen.forward(30)
pen.right(45)
pen.forward(100)
pen.right(45)
pen.forward(30)
pen.right(45)
pen.forward(170)
pen.right(45)
pen.forward(30)
pen.right(45)
pen.forward(100)
pen.right(45)
pen.forward(30)
pen.right(45)
pen.forward(80)
pen.end_fill()
pen.up()

#lingkaran biru
pen.right(90)
pen.forward(25)
pen.left(90)
pen.forward(40)
pen.right(90)
pen.forward(50)
pen.right(180)
pen.down()
pen.fillcolor('Blue')
pen.circle(35)


turtle.exitonclick()